name: Create PR

on:
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - id: write-changes
        name: Write Changes
        run: |
          echo "This is a test" >> README.md 

      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        env:
          PR_AUTHOR: github-actions[bot] <github-actions@users.noreply.github.com>
        with:
          token: ${{ steps.generate_token.outputs.token }}
          commit-message: Updated README.md
          branch: update-readme-${{ github.run_id }}
          body: |
            Updated README.md'
          title: "Updated README.md"
